[workspace]
members = ["."]
resolver = "3"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
rust-version = "1.92"
version = "0.1.0"

[workspace.dependencies]
gpui = { git = "https://github.com/berylorg/zed-fork.git", rev = "11e7d5c41d06f6378ec036fd881c7eb18011f0e7", default-features = false, features = ["windows-manifest"] }
gpui-scrollbar = { git = "https://github.com/berylorg/gpui-scrollbar.git", rev = "3c2d50c7f53259885749bd8bffc3e812043addd5" }
unicode-segmentation = { git = "https://github.com/berylorg/unicode-segmentation-fork.git", rev = "2badf6af53c261e0f39da75bd25036d45e6278d2" }

[package]
name = "gpui-text-input"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
test-support = []

[dependencies]
gpui.workspace = true
gpui-scrollbar.workspace = true
unicode-segmentation.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
